### ISSUE TITLE
Using Poornimant

### ISSUE THREAD

**Issue by androidanit** [bdsatish/drik-panchanga#7]
Namaskaram,

As you have mentioned -
By default, the month type is Amavasyanta (new moon to new moon) which is most prominent type of calendar used in South India.

Is there any way one can use Poornimant.
Is it bulit in code ? If yes, kindly guide about how to use.
If no, can it be added in code ?

Thanks

**Comment by bdsatish** [comment]
It's hardcoded for now, but pretty easy to change. I'll add some notes in README when I find time.

**Comment by androidanit** [comment]
Thanks for suggesting quick solution.
Somehow, after doing this change. I checked panchanga for location 'Mumbai' on date 31/10/2015

It produced errors with bracktrace as follows.

Traceback (most recent call last):
  File "E:/PythonProjects/drik-panchanga/gui.py", line 200, in calculate_panchanga
    mas = masa(jd, place)
  File "E:\PythonProjects\drik-panchanga\panchanga.py", line 361, in masa
    this_solar_month = raasi(last_new_moon)
  File "E:\PythonProjects\drik-panchanga\panchanga.py", line 397, in raasi
    s = solar_longitude(jd)
  File "E:\PythonProjects\drik-panchanga\panchanga.py", line 174, in <lambda>
    solar_longitude = lambda jd: sidereal_longitude(jd, swe.SUN)
  File "E:\PythonProjects\drik-panchanga\panchanga.py", line 170, in sidereal_longitude
    longi = swe.calc_ut(jd, planet, flag = swe.FLG_SWIEPH | swe.FLG_SIDEREAL)
swisseph.Error: SwissEph file 'seplm39342.se1' not found in PATH '/usr/share/swisseph:/usr/local/share/swisseph\'

**Comment by bdsatish** [comment]
It means the lagrange interpolation failed, gives negative dates, which the Swiss ephemeris cannot handle. I'll get back when I have time. (Or if you can figure out, make a pull request!)

**Comment by androidanit** [comment]
Sure, thanks. 
I guess we would need your help here as I seriously lack required knowledge regarding concepts used in program.

**Comment by androidanit** [comment]
Thanks Satish, for quick reply. 
I made changes as said and errors are gone.
But, the Poornimanta tithis are not always correct. 

Test Results for reference - 
Location is 'Mumbai' for all tests.

1. Date 1/11/2015
Amavasyanta Tithi - Ashwin Kr. Paksha. 6 (Correct)
Poornimanta tithi - Kartika Kr. Paksha. 6 (Correct)

2. Date 8/6/2015
Amavasyanta Tithi - Jyeshta Kr. Paksha. 6  (Correct)
Poornimanta tithi - Jyeshta Kr. Paksha. 6  (Incorrect - Correct tithi is Aashadha Kr. Paksha. 6)

3. Date 6/7/2015
Amavasyanta Tithi - Adhika Aashadh Kr. Paksha. 5 (Correct)
Poornimanta tithi - Aashadh Kr. Paksha. 5 (Incorrect - Adhika is not displayed)
